notifications:
  email: false
env:
  global:
    - OPENAS2_FILE_SYSTEM_RUN=False
matrix:
  include:
    - os: linux
      dist: xenial
      language: java
      before_install:
        - sudo apt-get update
        - sudo apt list | grep jdk
        - sudo apt-get -y install openjdk-8-jdk-headless
        - sudo update-alternatives --display java
      script: ./mvnw test
      
language: bash
sudo: required
services:
  - docker
script:
  - docker run -it -v $(pwd):/root/sources -w /root/sources maven:3.3.3-jdk-8 mvn clean install
